<?xml version="1.0" encoding="UTF-8"?>
<ecore:EPackage xmi:version="2.0" xmlns:xmi="http://www.omg.org/XMI" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
    xmlns:ecore="http://www.eclipse.org/emf/2002/Ecore" name="model" nsURI="http://softlang.org/megamodel" nsPrefix="mm">
  <eClassifiers xsi:type="ecore:EClass" name="Megamodel">
    <eStructuralFeatures xsi:type="ecore:EReference" name="imports" upperBound="-1"
        eType="#//Megamodel"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="eTypeDecls" upperBound="-1"
        eType="#//ETypeDecl" containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="rTypeDecls" upperBound="-1"
        eType="#//RTypeDecl" containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="eDecls" upperBound="-1"
        eType="#//EDecl" containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="rDecls" upperBound="-1"
        eType="#//RDecl" containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Decl" abstract="true"/>
  <eClassifiers xsi:type="ecore:EClass" name="NamedDecl" eSuperTypes="#//Decl">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="name" lowerBound="1" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="showname" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="ETypeDecl" eSuperTypes="#//NamedDecl">
    <eStructuralFeatures xsi:type="ecore:EReference" name="supertype" eType="#//EType"
        containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="RTypeDecl" eSuperTypes="#//NamedDecl">
    <eStructuralFeatures xsi:type="ecore:EReference" name="left" lowerBound="1" eType="#//EType"
        containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="right" lowerBound="1" eType="#//EType"
        containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="EDecl" eSuperTypes="#//NamedDecl">
    <eStructuralFeatures xsi:type="ecore:EReference" name="type" lowerBound="1" eType="#//EType"
        containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="dependent" lowerBound="1"
        eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EBoolean"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="parameter" lowerBound="1"
        eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EBoolean"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="RDecl" eSuperTypes="#//Decl">
    <eStructuralFeatures xsi:type="ecore:EReference" name="left" lowerBound="1" eType="#//EDecl"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="type" lowerBound="1" eType="#//RTypeDecl"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="right" lowerBound="1" eType="#//EDecl"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="EType">
    <eStructuralFeatures xsi:type="ecore:EReference" name="def" lowerBound="1" eType="#//ETypeDecl"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="many" lowerBound="1" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EBoolean"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="args" upperBound="-1" eType="#//EType"
        containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="AppDecl" eSuperTypes="#//Decl">
    <eStructuralFeatures xsi:type="ecore:EReference" name="function" lowerBound="1"
        eType="#//EDecl"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="input" lowerBound="1" eType="#//EDecl"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="output" lowerBound="1"
        eType="#//EDecl"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="FDecl" eSuperTypes="#//NamedDecl">
    <eStructuralFeatures xsi:type="ecore:EReference" name="domain" lowerBound="1"
        eType="#//EType" containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="codomain" lowerBound="1"
        eType="#//EType" containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="dependent" lowerBound="1"
        eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EBoolean"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="parameter" lowerBound="1"
        eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EBoolean"/>
  </eClassifiers>
</ecore:EPackage>
