<?xml version="1.0" encoding="UTF-8"?>
<ecore:EPackage xmi:version="2.0" xmlns:xmi="http://www.omg.org/XMI" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
    xmlns:ecore="http://www.eclipse.org/emf/2002/Ecore" name="model" nsURI="http://softlang.wikidot.com/megal" nsPrefix="model">
  <eAnnotations source="http://www.eclipse.org/emf/2002/Ecore">
    <details key="settingDelegates" value="org.eclipse.incquery.querybasedfeature"/>
  </eAnnotations>
  <eClassifiers xsi:type="ecore:EClass" name="Megamodel">
    <eStructuralFeatures xsi:type="ecore:EReference" name="eTypeDecls" upperBound="-1"
        eType="#//ETypeDecl" containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="rTypeDecls" upperBound="-1"
        eType="#//RTypeDecl" containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="rDecls" upperBound="-1"
        eType="#//RDecl" containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="eDecls" upperBound="-1"
        eType="#//EDecl" containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="name" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"
        changeable="false" volatile="true" transient="true" derived="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="imports" upperBound="-1"
        eType="#//Megamodel"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="importedEDecls" upperBound="-1"
        eType="#//EDecl" changeable="false" volatile="true" transient="true" derived="true"
        containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="importedRTypeDecls" upperBound="-1"
        eType="#//RTypeDecl" changeable="false" volatile="true" transient="true" derived="true"
        containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="importedRDecls" upperBound="-1"
        eType="#//RDecl" changeable="false" volatile="true" transient="true" derived="true"
        containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="importedETypeDecls" upperBound="-1"
        eType="#//ETypeDecl" changeable="false" volatile="true" transient="true" derived="true"
        containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="RDecl" abstract="true">
    <eStructuralFeatures xsi:type="ecore:EReference" name="from" lowerBound="1" eType="#//EDecl"
        changeable="false" volatile="true" transient="true" derived="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="to" lowerBound="1" eType="#//EDecl"
        changeable="false" volatile="true" transient="true" derived="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="type" lowerBound="1" eType="#//RTypeDecl"
        changeable="false" volatile="true" transient="true" derived="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="EDecl" abstract="true">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="name" lowerBound="1" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"
        changeable="false" volatile="true" transient="true" derived="true"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="isParameter" lowerBound="1"
        eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EBoolean" changeable="false"
        volatile="true" transient="true" derived="true"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="isDependent" lowerBound="1"
        eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EBoolean" changeable="false"
        volatile="true" transient="true" derived="true"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="showname" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"
        changeable="false" volatile="true" transient="true" derived="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="type" lowerBound="1" eType="#//ETypeRef"
        changeable="false" volatile="true" transient="true" derived="true" containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="RTypeDecl" abstract="true">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="name" lowerBound="1" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"
        changeable="false" volatile="true" transient="true" derived="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="fromDomain" lowerBound="1"
        eType="#//ETypeRef" changeable="false" volatile="true" transient="true" derived="true"
        containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="toDomain" lowerBound="1"
        eType="#//ETypeRef" changeable="false" volatile="true" transient="true" derived="true"
        containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="ETypeDecl" abstract="true">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="name" lowerBound="1" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"
        changeable="false" volatile="true" transient="true" derived="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="supertype" eType="#//ETypeRef"
        changeable="false" volatile="true" transient="true" derived="true" containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="isRoot" lowerBound="1"
        eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EBoolean" changeable="false"
        volatile="true" transient="true" derived="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Sugar" abstract="true" interface="true"/>
  <eClassifiers xsi:type="ecore:EClass" name="FunctionApplication" eSuperTypes="#//Sugar">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="name" lowerBound="1" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="param" lowerBound="1" eType="#//EDecl"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="result" lowerBound="1"
        eType="#//EDecl"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="ETypeRef">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="isMany" lowerBound="1"
        eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EBoolean"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="definition" lowerBound="1"
        eType="#//ETypeDecl"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="ExETypeDecl" eSuperTypes="#//ETypeDecl">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="exName" lowerBound="1"
        eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="exIsRoot" lowerBound="1"
        eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EBoolean"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="exSupertype" eType="#//ETypeRef"
        containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="ExEDecl" eSuperTypes="#//EDecl">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="exName" lowerBound="1"
        eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="exIsParameter" lowerBound="1"
        eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EBoolean"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="exIsDependent" lowerBound="1"
        eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EBoolean"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="exShowname" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="exType" lowerBound="1"
        eType="#//ETypeRef" containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="ExRTypeDecl" eSuperTypes="#//RTypeDecl">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="exName" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="exFromDomain" lowerBound="1"
        eType="#//ETypeRef" containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="exToDomain" lowerBound="1"
        eType="#//ETypeRef" containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="FunctionEDecl" eSuperTypes="#//EDecl">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="exName" lowerBound="1"
        eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="exIsParameter" lowerBound="1"
        eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EBoolean"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="exIsDependent" lowerBound="1"
        eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EBoolean"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="exShowname" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
  </eClassifiers>
</ecore:EPackage>
